name: CarPark
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  latlng: any
  flutter_localizations:
    sdk: flutter
  platform: ^3.1.0
  map: ^1.4.1
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  google_sign_in: ^6.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  shared_preferences: ^2.0.20
  floating_navbar: ^2.0.2
  firebase_database: ^10.1.1
  cloud_firestore: ^4.5.3
  geofence_flutter: ^2.0.0
  flutter_geofence: ^0.4.4
  location: ^4.4.0
  url_launcher: ^6.1.11
  google_fonts: ^2.1.0
  permission_handler: ^10.2.0
  flutter_map: ^4.0.0
  upi_india: ^3.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


  assets:
     - assets/images/logo.png
     - assets/images/g.png
     - assets/images/c1.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
